export const STRINGS = {
  enter_otp_here: 'Enter OTP here',
  continue: 'Continue',
  login: 'Login',
  signup: 'Sign Up',
  please_verify: 'Please Verify Your Mobile Number',
  please_enter: 'Please Enter Your Mobile Number',
  already_registered: 'Already Registered ?',
  requestOTP: 'Request OTP',
  otpSentSuccess: 'OTP sent successfully on',
  otpSent: 'OTP Sent',
  resendOtp: 'Resend OTP',
  noAccount: `Don't Have An Account ?`,
  almostThere: 'Almost There !',
  bitMore: `Let's know you a bit more`,
  awesomeWhat: `You're Awesome ! What should we call you.`,
  invalidEmailAddress: 'Invalid Email Id',
  invalidMobileNumber: 'Invalid Mobile Number',
  fieldRequired: 'Field is required',
  nameHint: 'Elon Musk',
  email: 'Email ID',
  emailHint: 'abc@gmail.com',
  optional: 'Optional',
  referralCode: 'Referral Code',
  alternativeMobile: 'Alternative Mobile No.',
  house_number: 'House No. (Optional)',
  house_number_hint: 'Enter house number',

  full_address: 'Full Address',
  full_address_hint: 'Enter full address',

  contact: 'Contact',
  contact_hint: '1234567890',

  // RAZOR PAY TEST CREDENTIAL - 01/11/2022
  RAZOR_PAY_KEY_ID: 'rzp_test_LAyG6lrl5x3XE0',
  RAZOR_PAY_KEY_SECRET: 'AFkDeXyyfORubnH7TNourriR',
};
